name: musix
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-190.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.2
  just_audio: ^0.9.37
  audio_video_progress_bar: any
  http: ^1.2.1
  shared_preferences: ^2.2.2
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.10
  flutter_bloc: ^8.1.3
  loading_indicator: ^3.1.0
  flutter_animate: ^4.5.0
  flutter_staggered_animations: ^1.1.1
  mini_music_visualizer: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 300

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 100
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 400
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 300

